# Generated by Django 5.2.8 on 2026-07-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(db_index=True, max_length=100)),
                ('value', models.DecimalField(db_index=True, decimal_places=2, max_digits=15)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['metric_name', 'recorded_at'], name='idx_analytics_metric_date'), models.Index(fields=['category', 'recorded_at'], name='idx_analytics_category_date')],
            },
        ),
    ]
