# Generated by Django 6.0.5 on 2026-07-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20260623_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='quantity',
            field=models.IntegerField(db_index=True),
        ),
    ]
