# Generated by Django 5.2.8 on 2026-07-17 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_staff_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='hr.staff'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='hr.staff'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hr.staff'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='hr.staff'),
        ),
        migrations.AddField(
            model_name='contract',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='hr.staff'),
        ),
        migrations.AddField(
            model_name='timeattendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hr.staff'),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='hr.staff'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['user', 'position'], name='idx_staff_user_position'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['department', 'is_active'], name='idx_staff_dept_active'),
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['employee', 'review_date'], name='idx_review_emp_date'),
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['rating', 'review_date'], name='idx_review_rating_date'),
        ),
        migrations.AddIndex(
            model_name='payrollrecord',
            index=models.Index(fields=['employee', 'period'], name='idx_payroll_emp_period'),
        ),
        migrations.AddIndex(
            model_name='payrollrecord',
            index=models.Index(fields=['payment_date', 'period'], name='idx_payroll_date_period'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee', 'status'], name='idx_leave_emp_status'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['status', 'start_date'], name='idx_leave_status_start'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['employee', 'contract_type'], name='idx_contract_emp_type'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status', 'start_date'], name='idx_contract_status_start'),
        ),
        migrations.AddIndex(
            model_name='timeattendance',
            index=models.Index(fields=['employee', 'date'], name='idx_attendance_emp_date'),
        ),
        migrations.AddIndex(
            model_name='timeattendance',
            index=models.Index(fields=['date', 'status'], name='idx_attendance_date_status'),
        ),
        migrations.AddConstraint(
            model_name='timeattendance',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_employee_date'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['employee', 'completion_date'], name='idx_training_emp_date'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['status', 'completion_date'], name='idx_training_status_date'),
        ),
    ]
