# Generated by Django 6.0.5 on 2026-07-15 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referrals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['patient', 'status'], name='idx_referral_patient_status'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referred_by', 'referral_date'], name='idx_referral_by_date'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['status', 'referral_date'], name='idx_referral_status_date'),
        ),
    ]
