# Generated by Django 5.2.8 on 2026-07-19 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_initial'),
        ('quality', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_reports', to='users.employee'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_reports', to='patients.patient'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['employee', 'incident_date'], name='idx_incident_emp_date'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['patient', 'incident_date'], name='idx_incident_patient_date'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['incident_type', 'incident_date'], name='idx_incident_type_date'),
        ),
    ]
