# Generated by Django 6.0.5 on 2026-07-15 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab', '0001_initial'),
        ('patients', '0001_initial'),
        ('users', '0001_initial'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrequest',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_ordered', to='users.employee'),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='lab_tech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_conducted', to='users.employee'),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.labtest'),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='visits.visits'),
        ),
        migrations.AddIndex(
            model_name='testrequest',
            index=models.Index(fields=['patient', 'status'], name='idx_lab_patient_status'),
        ),
        migrations.AddIndex(
            model_name='testrequest',
            index=models.Index(fields=['doctor', 'status'], name='idx_lab_doctor_status'),
        ),
        migrations.AddIndex(
            model_name='testrequest',
            index=models.Index(fields=['status', 'requested_at'], name='idx_lab_status_date'),
        ),
    ]
