# Generated by Django 5.2.8 on 2026-07-19 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('second_name', models.CharField(db_index=True, max_length=100)),
                ('third_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(db_index=True, max_length=10)),
                ('age', models.IntegerField(db_index=True)),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
            ],
            options={
                'ordering': ['first_name', 'second_name'],
                'indexes': [models.Index(fields=['first_name', 'second_name', 'phone_number'], name='idx_names_full')],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('employee_type', models.CharField(choices=[('ADMIN', 'ICT / Admin'), ('DOCTOR', 'Doctor'), ('CHEMIST', 'Pharmacist'), ('STORE_MANAGER', 'Store Manager'), ('QUALITY_ASSURANCE', 'Quality Assurance Officer'), ('TRIAGE', 'Triage Nurse'), ('NURSE', 'General Nurse (Wards)'), ('RECEPTIONIST', 'Receptionist'), ('ACCOUNTANT', 'Accountant'), ('LAB_TECH', 'Lab Technician')], db_index=True, default='DOCTOR', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_staff', models.BooleanField(db_index=True, default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.names')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
                'indexes': [models.Index(fields=['user', 'email'], name='idx_employee_user_email')],
            },
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['employee_type', 'is_active'], name='idx_users_role_active'),
        ),
    ]
