# Generated by Django 5.2.8 on 2025-11-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employee_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='employee_type',
            field=models.CharField(choices=[('ADMIN', 'ICT / Admin'), ('DOCTOR', 'Doctor'), ('CHEMIST', 'Pharmacist'), ('STORE_MANAGER', 'Store Manager'), ('TRIAGE', 'Triage Nurse'), ('NURSE', 'General Nurse (Wards)'), ('RECEPTIONIST', 'Receptionist'), ('ACCOUNTANT', 'Accountant'), ('LAB_TECH', 'Lab Technician')], default='DOCTOR', max_length=50),
        ),
    ]
