# Generated by Django 5.2.8 on 2026-07-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_employee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='employee_type',
            field=models.CharField(choices=[('ADMIN', 'ICT / Admin'), ('DOCTOR', 'Doctor'), ('CHEMIST', 'Pharmacist'), ('STORE_MANAGER', 'Store Manager'), ('QUALITY_ASSURANCE', 'Quality Assurance Officer'), ('TRIAGE', 'Triage Nurse'), ('NURSE', 'General Nurse (Wards)'), ('RECEPTIONIST', 'Receptionist'), ('ACCOUNTANT', 'Accountant'), ('LAB_TECH', 'Lab Technician')], default='DOCTOR', max_length=50),
        ),
    ]
