# Generated by Django 6.0.5 on 2026-07-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_employee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='employee_type',
            field=models.CharField(choices=[('ADMIN', 'ICT / Admin'), ('DOCTOR', 'Doctor'), ('CHEMIST', 'Pharmacist'), ('STORE_MANAGER', 'Store Manager'), ('QUALITY_ASSURANCE', 'Quality Assurance Officer'), ('TRIAGE', 'Triage Nurse'), ('NURSE', 'General Nurse (Wards)'), ('RECEPTIONIST', 'Receptionist'), ('ACCOUNTANT', 'Accountant'), ('LAB_TECH', 'Lab Technician')], db_index=True, default='DOCTOR', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
