# Generated by Django 6.0.5 on 2026-07-15 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(db_index=True, default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['status', 'start_date'], name='idx_operation_status_start')],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='operations.operation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['operation', 'status'], name='idx_activity_operation_status'), models.Index(fields=['status', 'created_at'], name='idx_activity_status_created')],
            },
        ),
    ]
