# Generated by Django 5.2.8 on 2026-07-19 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['status', 'start_date'], name='idx_operation_status_start'),
        ),
        migrations.AddField(
            model_name='activity',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='operations.operation'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['event_type', 'start_time'], name='idx_event_type_start'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['status', 'start_time'], name='idx_event_status_start'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['employee', 'start_time'], name='idx_event_employee_start'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['operation', 'status'], name='idx_activity_operation_status'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['status', 'created_at'], name='idx_activity_status_created'),
        ),
    ]
