# Generated by Django 5.2.8 on 2026-07-17 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['model_name', 'object_id', 'timestamp'], name='idx_audit_model_object_ts'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['action', 'timestamp'], name='idx_audit_action_ts'),
        ),
    ]
