# Generated by Django 5.2.8 on 2026-07-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(db_index=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['transaction_type', 'date'], name='idx_finance_type_date'), models.Index(fields=['category', 'date'], name='idx_finance_category_date')],
            },
        ),
    ]
