# Generated by Django 5.2.8 on 2025-11-20 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.names'),
        ),
    ]
