# Generated by Django 5.2.8 on 2026-07-19 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='users.names'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['name', 'register_date'], name='idx_patient_name_reg'),
        ),
    ]
