# Generated by Django 5.2.8 on 2026-07-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Fully Paid')], db_index=True, default='PENDING', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Credit/Debit Card'), ('INSURANCE', 'Insurance'), ('MPESA', 'M-Pesa')], db_index=True, default='CASH', max_length=20)),
                ('reference_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
