# Generated by Django 5.2.8 on 2026-07-17 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('patients', '0001_initial'),
        ('prescriptions', '0001_initial'),
        ('users', '0001_initial'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='issued_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_issued', to='users.employee'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prescriptions.prescription'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visits.visits'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to='users.employee'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['patient', 'status'], name='idx_invoice_patient_status'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issued_by', 'issued_at'], name='idx_invoice_issued'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'issued_at'], name='idx_invoice_status_date'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'payment_date'], name='idx_payment_invoice_date'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['received_by', 'payment_date'], name='idx_payment_received_date'),
        ),
    ]
