# Generated by Django 5.2.8 on 2026-07-17 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        ('patients', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField(blank=True, null=True)),
                ('triage_level', models.CharField(blank=True, max_length=50, null=True)),
                ('body_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bp_diastolic', models.IntegerField(blank=True, null=True)),
                ('bp_systolic', models.IntegerField(blank=True, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending (Triage/Doctor)'), ('CONSULTATION', 'Consultation'), ('LAB_WORK', 'Lab Investigation'), ('ADMITTED', 'In-Patient'), ('DISCHARGED', 'Discharged'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=50)),
                ('patient_type', models.CharField(choices=[('OPD', 'Out-Patient'), ('IPD', 'In-Patient')], db_index=True, default='OPD', max_length=10)),
                ('ward', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('bed_number', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('consultation_notes', models.TextField(blank=True, null=True)),
                ('pharmacy_notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.staff')),
                ('triage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_initial_triage', to='visits.triage')),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='WardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notes', models.TextField(help_text='Nursing notes / Observation')),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employee')),
                ('triage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='visits.triage')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward_logs', to='visits.visits')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='visits',
            index=models.Index(fields=['patient', 'status'], name='idx_visit_patient_status'),
        ),
        migrations.AddIndex(
            model_name='visits',
            index=models.Index(fields=['status', 'visit_date'], name='idx_visit_status_date'),
        ),
        migrations.AddIndex(
            model_name='wardlog',
            index=models.Index(fields=['visit', 'timestamp'], name='idx_wardlog_visit_ts'),
        ),
        migrations.AddIndex(
            model_name='wardlog',
            index=models.Index(fields=['nurse', 'timestamp'], name='idx_wardlog_nurse_ts'),
        ),
    ]
