# Generated by Django 5.2.8 on 2025-11-20 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField()),
                ('triage_level', models.CharField(max_length=50)),
                ('body_temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bp_diastolic', models.IntegerField()),
                ('bp_systolic', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('consultation_notes', models.TextField(blank=True, null=True)),
                ('pharmacy_notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employee')),
                ('triage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.triage')),
            ],
        ),
    ]
