# Generated by Django 5.2.8 on 2025-11-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triage',
            name='chief_complaint',
            field=models.TextField(blank=True, null=True),
        ),
    ]
