# Generated by Django 6.0.5 on 2026-07-16 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_initial'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.staff'),
        ),
    ]
