# Generated by Django 5.2.8 on 2025-11-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_alter_triage_chief_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONSULTATION', 'Consultation'), ('COMPLETED', 'Completed')], default='PENDING', max_length=50),
        ),
    ]
