# Generated by Django 5.2.8 on 2025-11-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_alter_visits_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='visits',
            name='bed_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='visits',
            name='patient_type',
            field=models.CharField(choices=[('OPD', 'Out-Patient'), ('IPD', 'In-Patient')], default='OPD', max_length=10),
        ),
        migrations.AddField(
            model_name='visits',
            name='ward',
            field=models.CharField(blank=True, help_text="Ward Name (e.g., 'Maternity', 'General Ward')", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visits',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending (Triage/Doctor)'), ('CONSULTATION', 'Consultation'), ('LAB_WORK', 'Lab Investigation'), ('ADMITTED', 'Admitted (In-Patient)'), ('DISCHARGED', 'Discharged'), ('COMPLETED', 'Completed')], default='PENDING', max_length=50),
        ),
    ]
