# Generated by Django 5.2.8 on 2025-11-21 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_employee_type'),
        ('visits', '0004_visits_bed_number_visits_patient_type_visits_ward_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('body_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bp_systolic', models.IntegerField(blank=True, null=True)),
                ('bp_diastolic', models.IntegerField(blank=True, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(help_text='Nursing notes / Observation')),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employee')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward_logs', to='visits.visits')),
            ],
        ),
    ]
