# Generated by Django 5.2.8 on 2025-11-21 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0005_wardlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wardlog',
            name='body_temp',
        ),
        migrations.RemoveField(
            model_name='wardlog',
            name='bp_diastolic',
        ),
        migrations.RemoveField(
            model_name='wardlog',
            name='bp_systolic',
        ),
        migrations.RemoveField(
            model_name='wardlog',
            name='heart_rate',
        ),
        migrations.AddField(
            model_name='wardlog',
            name='triage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='visits.triage'),
        ),
        migrations.AlterField(
            model_name='triage',
            name='body_temp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='bp_diastolic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='bp_systolic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='triage_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='visits',
            name='triage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_initial_triage', to='visits.triage'),
        ),
        migrations.AlterField(
            model_name='visits',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
