# Generated by Django 6.0.5 on 2026-07-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0006_remove_wardlog_body_temp_remove_wardlog_bp_diastolic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='bed_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visits',
            name='patient_type',
            field=models.CharField(choices=[('OPD', 'Out-Patient'), ('IPD', 'In-Patient')], db_index=True, default='OPD', max_length=10),
        ),
        migrations.AlterField(
            model_name='visits',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending (Triage/Doctor)'), ('CONSULTATION', 'Consultation'), ('LAB_WORK', 'Lab Investigation'), ('ADMITTED', 'Admitted (In-Patient)'), ('DISCHARGED', 'Discharged'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='visits',
            name='visit_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='visits',
            name='ward',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wardlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
