// src/pages/Reports.jsx
import React, { useState, useEffect } from 'react';
import { reportsService } from '../api/reportsService';
import './Reports.css';

function Reports() {
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [selected, setSelected] = useState(null);

  const load = async () => {
    setLoading(true);
    try {
      const res = await reportsService.getReports();
      setItems(res.data.results || res.data || []);
      setError(null);
    } catch (e) {
      setError('Failed to load reports.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { load(); }, []);

  const openReport = async (id) => {
    try {
      const res = await reportsService.getReport(id);
      setSelected(res.data);
    } catch (e) {
      setError('Failed to open report.');
    }
  };

  return (
    <div className="reports-page">
      <div className="staff-header-row"><h2>Reports</h2></div>
      {error && <p className="page-error">{error}</p>}

      {selected ? (
        <div className="report-detail wide-card">
          <button className="back-btn" onClick={() => setSelected(null)}>&larr; Back to list</button>
          <h3>{selected.title}</h3>
          <p className="subtext">
            {selected.report_type} · generated by {selected.generated_by ?? '—'} · {selected.generated_at ?? ''}
          </p>
          <pre className="report-content">{selected.content}</pre>
        </div>
      ) : loading ? (
        <p className="hr-muted">Loading…</p>
      ) : items.length === 0 ? (
        <p className="hr-muted">No reports generated.</p>
      ) : (
        <table className="hr-table">
          <thead>
            <tr><th>Title</th><th>Type</th><th>Generated By</th><th>Date</th><th></th></tr>
          </thead>
          <tbody>
            {items.map((r) => (
              <tr key={r.id}>
                <td>{r.title}</td>
                <td><span className="status-badge status-default">{r.report_type}</span></td>
                <td>{r.generated_by ?? '—'}</td>
                <td>{r.generated_at ?? '—'}</td>
                <td>
                  <button className="mc-btn btn-sm btn-ghost" onClick={() => openReport(r.id)}>View</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
}

export default Reports;
