# Generated by Django 6.0.5 on 2026-07-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('report_type', models.CharField(choices=[('summary', 'Summary'), ('detailed', 'Detailed'), ('custom', 'Custom')], db_index=True, max_length=20)),
                ('content', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
