# Generated by Django 6.0.5 on 2026-07-15 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type', 'generated_at'], name='idx_report_type_date'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['generated_by', 'generated_at'], name='idx_report_by_date'),
        ),
    ]
